[package]
name = "uniqna"
version = "0.1.0"
edition = "2018"
authors = [ "Daniel Dulaney <dulaney.daniel@gmail.com>" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
